In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv('topics.csv')
df.head()

Topic       Type of topic  \
0                  12 years a slave (Motion picture)               title   
1  16th Street Baptist Church Bombing (Birmingham...  meeting/conference   
2  16th Street Baptist Church Bombing, Birmingham...        general term   
3  16th Street Baptist Church Bombing, Birmingham...        general term   
4                                          1775-1783  chronological term   

   BL record ID Type of resource                            Content type  \
0      18260815        Monograph                Language material ; Text   
1      19043352        Monograph                Language material ; Text   
2      19043352        Monograph                Language material ; Text   
3      19381865        Monograph  Language material ; Still image ; Text   
4      19057287        Monograph                Language material ; Text   

     Material type BNB number           ISBN                      Name  \
0           Volume  GBB871718  9780393264241          Northup, Solomon   
1  Online resource  GBB8H0200  9783319471365           Gill, Sandra K.   
2  Online resource  GBB8H0200  9783319471365           Gill, Sandra K.   
3           Volume  GBB976507  9781250201447  Jones, Doug (G. Douglas)   
4           Volume        NaN  9781945572425           Glickman, James   

  Dates associated with name  ...     Place of publication  \
0    1808-approximately 1863  ...                 New York   
1                        NaN  ...                 New York   
2                        NaN  ...                 New York   
3                      1954-  ...                 New York   
4                        NaN  ...  Los Angeles, California   

                Publisher Date of publication  \
0            W. W. Norton                2017   
1      Palgrave Macmillan                2017   
2      Palgrave Macmillan                2017   
3                  Points                2019   
4  Rare Bird ; Vireo Book                2017   

                                  Edition  \
0                                     NaN   
1                                     NaN   
2                                     NaN   
3                                     NaN   
4  First trade paperback original edition   

                                Physical description Dewey classification  \
0  xx, 410 pages, black and white illustrations, ...           303.362092   
1                                  1 online resource             976.1781   
2                                  1 online resource             976.1781   
3  xix, 363 pages, 16 of plates, black and white ...   323.11960730761781   
4                                   472 pages, 22 cm                813.6   

     BL shelfmark                                   Genre Languages Notes  
0  YC.2018.a.5558                               Biography   English   NaN  
1   ELD.DS.323508                                 History   English   NaN  
2   ELD.DS.323508                                 History   English   NaN  
3   YD.2021.a.765                                     NaN   English   NaN  
4   YD.2019.a.803  Fiction ; Historical fiction ; History   English   NaN  

[5 rows x 28 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39865 entries, 0 to 39864
Data columns (total 28 columns):
 #   Column                      Non-Null Count  Dtype 
---  ------                      --------------  ----- 
 0   Topic                       39865 non-null  object
 1   Type of topic               39865 non-null  object
 2   BL record ID                39865 non-null  int64 
 3   Type of resource            39865 non-null  object
 4   Content type                39865 non-null  object
 5   Material type               39845 non-null  object
 6   BNB number                  29887 non-null  object
 7   ISBN                        39047 non-null  object
 8   Name                        33784 non-null  object
 9   Dates associated with name  14249 non-null  object
 10  Type of name                33784 non-null  object
 11  Role                        11329 non-null  object
 12  All names                   39722 non-null  object
 13  Title                       39865 non-null  ob

In [4]:
df=df[['Title']]
df.head()

Title
0                               Twelve years a slave
1  Whites recall the civil rights movement in Bir...
2  Whites recall the civil rights movement in Bir...
3  Bending toward justice : the Birmingham church...
4                                     Crossing point

In [5]:
sent_list=df.values.tolist()
sentences=[]
for i in sent_list:
    sentences.append(i[0])
sentences

['Twelve years a slave',
 "Whites recall the civil rights movement in Birmingham : we didn't know it was history until after it happened",
 "Whites recall the civil rights movement in Birmingham : we didn't know it was history until after it happened",
 'Bending toward justice : the Birmingham church bombing that changed the course of civil rights',
 'Crossing point',
 'Destiny and race : selected writings, 1840-1898',
 'Through darkness to light : photographs along the underground railroad : a photographic essay',
 'Freedom : a fable. A curious interpretation of the wit of a negress in troubled times, with illustrations',
 "Jefferson Davis's final campaign : Confederate nationalism and the fight to arm slaves",
 'A walking tour of the Black presence in San Francisco during the nineteenth century : a Black History Week event',
 'The colonization of freed African Americans in Suriname : archival sources relating to the U.S.-Dutch negotiations, 1860-1866',
 'The original Black elite : Da

Bag-Of-Word

In [6]:

from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(max_features = 20)  ##give it a max features as 3
Bagofwords = cv.fit_transform(sentences).toarray()

print(Bagofwords)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 1 0]
 ...
 [0 0 1 ... 0 2 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]]


TF_IDF

In [7]:
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import CountVectorizer

tfIdfTransformer = TfidfTransformer(use_idf=True)
countVectorizer = CountVectorizer()
wordCount = countVectorizer.fit_transform(sentences)
newTfIdf = tfIdfTransformer.fit_transform(wordCount)
df = pd.DataFrame(newTfIdf[0].T.todense(), index=countVectorizer.get_feature_names_out(), columns=["TF-IDF"])
df = df.sort_values('TF-IDF', ascending=False)
df.head(5)

TF-IDF
twelve    0.688951
years     0.557777
slave     0.462852
parallel  0.000000
parole    0.000000

One Hot Vector Representation

In [8]:
sentences1=sentences[:5]
print(sentences1)

['Twelve years a slave', "Whites recall the civil rights movement in Birmingham : we didn't know it was history until after it happened", "Whites recall the civil rights movement in Birmingham : we didn't know it was history until after it happened", 'Bending toward justice : the Birmingham church bombing that changed the course of civil rights', 'Crossing point']


In [9]:

token_index = {}
#Create a counter for counting the number of key-value pairs in the token_length
counter = 0

# Select the elements of the samples which are the two sentences
for sample in sentences1:                                      
    for considered_word in sample.split():
        if considered_word not in token_index:
            token_index.update({considered_word : counter + 1}) 
            counter = counter + 1    

In [10]:
print(token_index)

{'Twelve': 1, 'years': 2, 'a': 3, 'slave': 4, 'Whites': 5, 'recall': 6, 'the': 7, 'civil': 8, 'rights': 9, 'movement': 10, 'in': 11, 'Birmingham': 12, ':': 13, 'we': 14, "didn't": 15, 'know': 16, 'it': 17, 'was': 18, 'history': 19, 'until': 20, 'after': 21, 'happened': 22, 'Bending': 23, 'toward': 24, 'justice': 25, 'church': 26, 'bombing': 27, 'that': 28, 'changed': 29, 'course': 30, 'of': 31, 'Crossing': 32, 'point': 33}


In [11]:
results  = np.zeros(shape = (len(sentences1),
                            max(token_index.values()) + 1))  
print(results)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [12]:
def str_list(Input_Sentence): 
    output_ = Input_Sentence.split()
    return output_
sentence=[]
for i in sent_list:
    sentence.append(str_list(i[0]))
    
for i in range(0,5):
    for j in sentence[i]:
        results[i][token_index[j]]=1
print(results)

[[0. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 1. 1.]]


CBOW

In [13]:
from sklearn.feature_extraction.text import CountVectorizer
text = ["I love writing code in Python. I love Python code",
        "I hate writing code in Java. I hate Java code"]
df = pd.DataFrame({'review': ['review1', 'review2'], 'text':text})
cv = CountVectorizer(stop_words='english')
cv_matrix = cv.fit_transform(df['text'])
df_dtm = pd.DataFrame(cv_matrix.toarray(),
                      index=df['review'].values,
                      columns=cv.get_feature_names_out())
df_dtm

code  hate  java  love  python  writing
review1     2     0     0     2       2        1
review2     2     2     2     0       0        1

SkipGram

In [14]:
import pandas as pd
import numpy as np
import re
import nltk
import matplotlib.pyplot as plt
pd.options.display.max_colwidth = 200
%matplotlib inline

In [15]:
corpus = ['The sky is blue and beautiful.',
          'Love this blue and beautiful sky!',
          'The quick brown fox jumps over the lazy dog.',
          "A king's breakfast has sausages, ham, bacon, eggs, toast and beans",
          'I love green eggs, ham, sausages and bacon!',
          'The brown fox is quick and the blue dog is lazy!',
          'The sky is very blue and the sky is very beautiful today',
          'The dog is lazy but the brown fox is quick!'    
]
labels = ['weather', 'weather', 'animals', 'food', 'food', 'animals', 'weather', 'animals']

corpus = np.array(corpus)
corpus_df = pd.DataFrame({'Document': corpus, 
                          'Category': labels})
corpus_df = corpus_df[['Document', 'Category']]
corpus_df

Document Category
0                                      The sky is blue and beautiful.  weather
1                                   Love this blue and beautiful sky!  weather
2                        The quick brown fox jumps over the lazy dog.  animals
3  A king's breakfast has sausages, ham, bacon, eggs, toast and beans     food
4                         I love green eggs, ham, sausages and bacon!     food
5                    The brown fox is quick and the blue dog is lazy!  animals
6            The sky is very blue and the sky is very beautiful today  weather
7                         The dog is lazy but the brown fox is quick!  animals

In [16]:
wpt = nltk.WordPunctTokenizer()
stop_words = nltk.corpus.stopwords.words('english')

def normalize_document(doc):
    # lower case and remove special characters\whitespaces
    doc = re.sub(r'[^a-zA-Z\s]', '', doc, re.I|re.A)
    doc = doc.lower()
    doc = doc.strip()
    # tokenize document
    tokens = wpt.tokenize(doc)
    # filter stopwords out of document
    filtered_tokens = [token for token in tokens if token not in stop_words]
    # re-create document from filtered tokens
    doc = ' '.join(filtered_tokens)
    return doc

normalize_corpus = np.vectorize(normalize_document)

In [17]:
nltk.download('gutenberg')
nltk.download('punkt')

[nltk_data] Downloading package gutenberg to
[nltk_data]     C:\Users\91983\AppData\Roaming\nltk_data...
[nltk_data]   Package gutenberg is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\91983\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [18]:
from nltk.corpus import gutenberg
from string import punctuation

bible = gutenberg.sents('bible-kjv.txt') 
remove_terms = punctuation + '0123456789'

norm_bible = [[word.lower() for word in sent if word not in remove_terms] for sent in bible]
norm_bible = [' '.join(tok_sent) for tok_sent in norm_bible]
norm_bible = filter(None, normalize_corpus(norm_bible))
norm_bible = [tok_sent for tok_sent in norm_bible if len(tok_sent.split()) > 2]

print('Total lines:', len(bible))
print('\nSample line:', bible[10])
print('\nProcessed line:', norm_bible[10])

Total lines: 30103

Sample line: ['1', ':', '6', 'And', 'God', 'said', ',', 'Let', 'there', 'be', 'a', 'firmament', 'in', 'the', 'midst', 'of', 'the', 'waters', ',', 'and', 'let', 'it', 'divide', 'the', 'waters', 'from', 'the', 'waters', '.']

Processed line: god said let firmament midst waters let divide waters waters


In [19]:
from keras.preprocessing import text

tokenizer = text.Tokenizer()
tokenizer.fit_on_texts(norm_bible)

word2id = tokenizer.word_index
id2word = {v:k for k, v in word2id.items()}

vocab_size = len(word2id) + 1 
embed_size = 100

wids = [[word2id[w] for w in text.text_to_word_sequence(doc)] for doc in norm_bible]
print('Vocabulary Size:', vocab_size)
print('Vocabulary Sample:', list(word2id.items())[:10])

Vocabulary Size: 12425
Vocabulary Sample: [('shall', 1), ('unto', 2), ('lord', 3), ('thou', 4), ('thy', 5), ('god', 6), ('ye', 7), ('said', 8), ('thee', 9), ('upon', 10)]


In [20]:
from keras.preprocessing.sequence import skipgrams

# generate skip-grams
skip_grams = [skipgrams(wid, vocabulary_size=vocab_size, window_size=10) for wid in wids]

# view sample skip-grams
pairs, labels = skip_grams[0][0], skip_grams[0][1]
for i in range(10):
    print("({:s} ({:d}), {:s} ({:d})) -> {:d}".format(
          id2word[pairs[i][0]], pairs[i][0], 
          id2word[pairs[i][1]], pairs[i][1], 
          labels[i]))

(james (1154), king (13)) -> 1
(king (13), usury (1912)) -> 0
(king (13), james (1154)) -> 1
(king (13), aloof (10459)) -> 0
(james (1154), silence (1471)) -> 0
(bible (5766), king (13)) -> 1
(bible (5766), boanerges (11446)) -> 0
(king (13), bible (5766)) -> 1
(james (1154), seventeenth (4260)) -> 0
(james (1154), bible (5766)) -> 1
